---

- name: Install chart (if release does NOT exist yet)
  command: |
    helm install {{ item.item.chart }} 
      {% if helm_kubectl_context is defined and helm_kubectl_context %}
      --kube-context {{ helm_kubectl_context }}
      {% endif %}
      --dry-run
      --version {{ item.item.chart_version }}
      --namespace {{ item.item.namespace }}
      --values {{ item.path }}
      --name-template {{ item.item.release }}
  with_items: "{{ helm_charts }}"
  when: item.item.release not in helm_release_names
  register: _helm_install_chart
  check_mode: False
  changed_when: False

- name: Show dry mode results
  debug:
    msg:
      cmd: "{{ item.cmd | join(' ') }}"
      stdout: "{{ item.stdout }}"
      stderr: "{{ item.stderr }}"
      return_code: "{{ item.rc }}"
  with_items: "{{ _helm_install_chart.results }}"
  # Run only for items which were not skipped
  when: (item.skipped is not defined) or (not item.skipped)

- name: Update chart (if release exist already)
  command: |
    helm upgrade
      {% if helm_kubectl_context is defined and helm_kubectl_context %}
      --kube-context {{ helm_kubectl_context }}
      {% endif %}
      --dry-run
      --version {{ item.item.chart_version }}
      --namespace {{ item.item.namespace }}
      --values {{ item.path }}
      {{ item.item.release }} {{ item.item.chart }}
  with_items: "{{ helm_charts }}"
  when: item.item.release in helm_release_names
  register: _helm_upgrade_chart
  check_mode: False
  changed_when: False

- name: Show dry mode results
  debug:
    msg:
      cmd: "{{ item.cmd | join(' ') }}"
      stdout: "{{ item.stdout }}"
      stderr: "{{ item.stderr }}"
      return_code: "{{ item.rc }}"
  with_items: "{{ _helm_upgrade_chart.results }}"
  # Run only for items which were not skipped
  when: (item.skipped is not defined) or (not item.skipped)
